name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ssh
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_ADDR: ${{ secrets.SSH_ADDR }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_COMMAND: ${{ secrets.SSH_COMMAND }}
      run: 
        echo "$SECRET_KEY" > secret_key  
        chmod 600 secret_key
        ssh -oStrictHostKeyChecking=no ${SSH_USER}@${SSH_ADDR} -p $SSH_PORT -i secret_key "$SSH_COMMAND"
